resources: 
- name: hello-world-source
  type: git
  check_every: 2m
  source:
    uri: https://gitub.com/tatt00u/concourse-class.git
    branch: master
- name: 3m
  type: time
  source: {interval: 10m}
jobs:
- name: hello-world
  plan:
  - get: hello-world-source
    trigger: true
  - get: 3m
    trigger: true
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Hello, world14!"]
